services:
  tfm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tfm
    # Acceso a la GPU AMD (Comentado para Laptop/APU)
    # devices:
    #   - "/dev/kfd:/dev/kfd"
    #   - "/dev/dri:/dev/dri"
    shm_size: '2gb' # Reducido para laptop
    # Mantenemos el contenedor abierto para interactuar
    tty: true
    stdin_open: true
    # Sincronización de archivos (Host:Contenedor)
    volumes:
      - ./compartida:/compartida
    # Puerto para Jupyter Lab
    ports:
      - "8888:8888"
    # shm_size: '8gb'
    environment:
      - PYTHONUNBUFFERED=1
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''